import { guroColors } from "./guroColors";

export const themeDefinitions = {
  "guro-blue": {
    primary: guroColors.classicBlue,
    "primary-content": guroColors.white,
    secondary: guroColors.classicSecondary,
    "secondary-content": guroColors.white,
    accent: guroColors.warning,
    "accent-content": guroColors.white,
    neutral: guroColors.slate900,
    "neutral-content": guroColors.white,
    "base-100": guroColors.white,
    "base-200": guroColors.slate50,
    "base-300": guroColors.slate300,
    "base-content": guroColors.slate900,
    info: guroColors.classicBlue,
    "info-content": guroColors.white,
    success: guroColors.success,
    "success-content": guroColors.white,
    warning: guroColors.warning,
    "warning-content": guroColors.white,
    error: guroColors.error,
    "error-content": guroColors.white,
    sidebar: guroColors.white,
    "sidebar-content": guroColors.slate900,
    "sidebar-muted": guroColors.slate500,
    "sidebar-border": guroColors.slate300,
    "sidebar-hover": guroColors.slate100,
    "sidebar-active": guroColors.slate100,
    "sidebar-active-content": guroColors.slate900,
    "sidebar-accent": guroColors.classicBlue,
  },
  "guro-brand": {
    primary: guroColors.burgundyMain,
    "primary-content": guroColors.white,
    secondary: guroColors.burgundySoft,
    "secondary-content": guroColors.white,
    accent: guroColors.gold,
    "accent-content": guroColors.slate900,
    neutral: guroColors.slate900,
    "neutral-content": guroColors.white,
    "base-100": guroColors.white,
    "base-200": guroColors.slate50,
    "base-300": guroColors.slate300,
    "base-content": guroColors.slate900,
    info: guroColors.burgundy,
    "info-content": guroColors.white,
    success: guroColors.success,
    "success-content": guroColors.white,
    warning: guroColors.warning,
    "warning-content": guroColors.white,
    error: guroColors.error,
    "error-content": guroColors.white,
    sidebar: guroColors.burgundyDark,
    "sidebar-content": guroColors.white,
    "sidebar-muted": guroColors.slate200,
    "sidebar-border": guroColors.burgundy,
    "sidebar-hover": guroColors.burgundy,
    "sidebar-active": guroColors.gold,
    "sidebar-active-content": guroColors.burgundyDark,
    "sidebar-accent": guroColors.burgundyDark,
  },
  "guro-night": {
    primary: guroColors.nightPrimary,
    "primary-content": guroColors.white,
    secondary: guroColors.nightSecondary,
    "secondary-content": guroColors.nightContent,
    accent: guroColors.nightAccent,
    "accent-content": guroColors.nightAccentContent,
    neutral: guroColors.nightNeutral,
    "neutral-content": guroColors.nightContent,
    "base-100": guroColors.nightSurface,
    "base-200": guroColors.nightBackground,
    "base-300": guroColors.nightBorderStrong,
    "base-content": guroColors.nightContent,
    info: guroColors.nightInfo,
    "info-content": guroColors.nightNeutral,
    success: guroColors.nightSuccess,
    "success-content": guroColors.nightNeutral,
    warning: guroColors.nightAccent,
    "warning-content": guroColors.nightAccentContent,
    error: guroColors.nightError,
    "error-content": guroColors.nightNeutral,
    sidebar: guroColors.nightSurface,
    "sidebar-content": guroColors.nightContent,
    "sidebar-muted": guroColors.slate300,
    "sidebar-border": guroColors.nightBorderStrong,
    "sidebar-hover": guroColors.nightBorder,
    "sidebar-active": guroColors.nightBorder,
    "sidebar-active-content": guroColors.nightContent,
    "sidebar-accent": guroColors.nightInfo,
  }
};

export const themeOptions = [
  { id: "guro-blue", label: "Classic Light", mode: "light" },
  { id: "guro-brand", label: "GURO Brand", mode: "light" },
  { id: "guro-night", label: "GURO Night", mode: "dark" },
];

export const defaultTheme = "guro-blue";
